# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Terence Chen
title: Terence's Blog
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog for studying.
baseurl: ""
github_username:  terenceluffy
rss_path: source/
url: http://terenceluffy.github.io
production_url: http://terenceluffy.github.io
repo: https://github.com/terenceLuffy
author:
  name      : Terence Chen
  email: terenceluffy@gmail.com
  image     : /assets/images/author.jpg
  url: http://terenceluffy.github.io # the base hostname & protocol for your site
  github  : https://github.com/terenceLuffy
  linkedin  : https://ca.linkedin.com/in/terence-chen-13955248

thought:
  text: I have no special talent. I am only passionately curious.
  author: Terence Chen
# Build settings
markdown: kramdown
highlighter : pygments
permalink   : /:title/
source:      source
destination: _site

paginate: 10
comments: true
paginate_path: "/page/:num"
domain_name: terence.chen
disqus_shortname: terencechen


# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
